apiVersion: v1
kind: Namespace
metadata:
  name: omniview-test-apps
---
apiVersion: v1
kind: Namespace
metadata:
  name: omniview-test-batch
---
apiVersion: v1
kind: Namespace
metadata:
  name: omniview-test-infra
